In [1]:
from bs4 import BeautifulSoup
import requests
import selenium
import pandas as pd

In [2]:
!pip install html5lib
!pip install lxml

Requirement already satisfied: html5lib in c:\anaconda\lib\site-packages (1.1)
Requirement already satisfied: webencodings in c:\anaconda\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in c:\anaconda\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: lxml in c:\anaconda\lib\site-packages (4.8.0)

In [3]:
from selenium import webdriver
browser = webdriver.Chrome()

In [4]:
driver = webdriver.Chrome()

In [11]:
url = 'http://wdi.worldbank.org/table/4.2'

In [12]:
driver.get(url)

In [13]:
sopa = BeautifulSoup(driver.page_source)

In [14]:
datos_tabla1 = sopa.select('table')

In [15]:
datos_tabla1

[<table border="0" cellpadding="0" cellspacing="0" class="headerLayout"><tbody><tr><td><div class="sectionLogo economy" style="background:url(../views/images/template/economy_blue.png) no-repeat left"></div></td><td><div class="year-sectionName"><div class="year"><a href="http://data.worldbank.org/data-catalog/world-development-indicators"></a></div><div class="clrBoth"></div><div class="sectionName">Economy</div><div class="clrBoth"></div><div class="clrBoth"></div></div></td><td><div class="tableTitle"><div class="tableNumber"><span id="tableSection">4.2</span></div></div></td><td><div class="tableTitle"><div class="titleTxt">
                                         World Development Indicators:
                                         <span id="report_heading">Structure of value added</span></div></div></td><td></td></tr></tbody></table>,
 <table border="0" cellpadding="0" cellspacing="0" class="indicators-table" id="fixedTable"><caption id="report_caption" style="display: none;">Structure of value added </caption><tbody><tr class="level0"><th class="first" style="width: 160px;"></th><th class="separator" colspan="2"><div class="spacer mark"><a data-text="Metadata:Gross domestic product" href="javascript:void(0)" onclick="loadWDIMetaData('NY.GDP.MKTP.CD', 'S', 'Series', 'Gross domestic product', 'Gross domestic product@Agriculture@Industry@Manufacturing@Services@', 'NY.GDP.MKTP.CD@NV.AGR.TOTL.ZS@NV.IND.TOTL.ZS@NV.IND.MANF.ZS@NV.SRV.TOTL.ZS@')">Gross domestic product</a></div></th><th class="separator" colspan="2"><div class="spacer mark"><a data-text="Metadata:Agriculture" href="javascript:void(0)" onclick="loadWDIMetaData('NV.AGR.TOTL.ZS', 'S', 'Series', 'Agriculture', 'Gross domestic product@Agriculture@Industry@Manufacturing@Services@', 'NY.GDP.MKTP.CD@NV.AGR.TOTL.ZS@NV.IND.TOTL.ZS@NV.IND.MANF.ZS@NV.SRV.TOTL.ZS@')">Agriculture</a></div></th><th class="separator" colspan="2"><div class="spacer mark"><a data-text="Metadata:Industry" href="javascript:void(0)" onclick="loadWDIMetaData('NV.IND.TOTL.ZS', 'S', 'Series', 'Industry', 'Gross domestic product@Agriculture@Industry@Manufacturing@Services@', 'NY.GDP.MKTP.CD@NV.AGR.TOTL.ZS@NV.IND.TOTL.ZS@NV.IND.MANF.ZS@NV.SRV.TOTL.ZS@')">Industry</a></div></th><th class="separator" colspan="2"><div class="spacer mark"><a data-text="Metadata:Manufacturing" href="javascript:void(0)" onclick="loadWDIMetaData('NV.IND.MANF.ZS', 'S', 'Series', 'Manufacturing', 'Gross domestic product@Agriculture@Industry@Manufacturing@Services@', 'NY.GDP.MKTP.CD@NV.AGR.TOTL.ZS@NV.IND.TOTL.ZS@NV.IND.MANF.ZS@NV.SRV.TOTL.ZS@')">Manufacturing</a></div></th><th class="separator" colspan="2"><div class="spacer mark"><a data-text="Metadata:Services" href="javascript:void(0)" onclick="loadWDIMetaData('NV.SRV.TOTL.ZS', 'S', 'Series', 'Services', 'Gross domestic product@Agriculture@Industry@Manufacturing@Services@', 'NY.GDP.MKTP.CD@NV.AGR.TOTL.ZS@NV.IND.TOTL.ZS@NV.IND.MANF.ZS@NV.SRV.TOTL.ZS@')">Services</a></div></th></tr><tr class="level1"><th class="first"></th><th class="separator" colspan="2"><div class="spacer"></div></th><th class="separator" colspan="2"><div class="spacer"></div></th><th class="separator" colspan="2"><div class="spacer"></div></th><th class="separator" colspan="2"><div class="spacer"></div></th><th class="separator" colspan="2"><div class="spacer"></div></th></tr><tr class="level2"><th class="first"></th><th class="separator" colspan="2"><div class="spacer">$ billions</div></th><th class="separator" colspan="2"><div class="spacer">% of GDP </div></th><th class="separator" colspan="2"><div class="spacer">% of GDP </div></th><th class="separator" colspan="2"><div class="spacer">% of GDP </div></th><th class="separator" colspan="2"><div class="spacer">% of GDP </div></th></tr><tr class="level3"><th class="first"></th><th><div class="spacer">2010</div></th><th class="separator"><div class="spacer">2020</div></th><th><div class="spacer">2010</div></th><th class="separator"><div class="spacer">2020</div></th><th><div class="spacer">2010</div></th><th class="separator"><div class="spacer">2020</div></th><th><div class="spacer">2010</div></th><th class="separator"><div class="spacer">2020</div></th><th><div class="spacer">2010</div></th><th class="separator"><div class="spacer">2020</div></th></tr></tbody></table>,

In [20]:
df = pd.read_html(str(sopa.select('div.scrollable')[0]))[0]

In [21]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,..,..,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,..,0.6,..,12.7,..,3.7,..,79.8

In [37]:
df.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [44]:
df_header = pd.read_html(str(sopa.select('div.fixed')[0]))[0]

In [45]:
df_header.head()

Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1, Unnamed: 0_level_2), (Gross domestic product, $ billions, 2010), (Gross domestic product, $ billions, 2020), (Agriculture, % of GDP, 2010), (Agriculture, % of GDP, 2020), (Industry, % of GDP, 2010), (Industry, % of GDP, 2020), (Manufacturing, % of GDP, 2010), (Manufacturing, % of GDP, 2020), (Services, % of GDP, 2010), (Services, % of GDP, 2020)]
Index: []

In [55]:
df.rename({'País': 0}, inplace = True)
df

,País,1,2,3,4,5,6,7,8,9,10
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,..,..,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,..,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [60]:
df.columns = ["Country", "GDP $billions 2010", "GDP $billions 2020", "Agriculture GDP% 2010", "Agriculture GDP% 2020", "Industry GDP% 2010", "Industry GDP% 2020", "Manufacturing GDP% 2010", "Manufacturing GDP% 2020", "Services GDP% 2010", "Services GDP% 2020"]
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,..,..,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,..,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [68]:
df.dtypes

Country                    object
GDP $billions 2010         object
GDP $billions 2020         object
Agriculture GDP% 2010      object
Agriculture GDP% 2020      object
Industry GDP% 2010         object
Industry GDP% 2020         object
Manufacturing GDP% 2010    object
Manufacturing GDP% 2020    object
Services GDP% 2010         object
Services GDP% 2020         object
dtype: object

In [92]:
df.replace(['..'], 0.0)

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,0.0,0.0,0.0,0.0,7.2,12.2,0.0,0.0
4,Andorra,3.4,2.9,0.0,0.6,0.0,12.7,0.0,3.7,0.0,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [96]:
df['GDP $billions 2010'] = pd.to_numeric(df['GDP $billions 2010'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,..,..,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,..,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [97]:
df['GDP $billions 2010'] = df['GDP $billions 2010'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,..,..,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,..,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [98]:
df['GDP $billions 2020'] = pd.to_numeric(df['GDP $billions 2020'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,..,..,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,..,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [99]:
df['GDP $billions 2020'] = df['GDP $billions 2020'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,..,..,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,..,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [100]:
df['Agriculture GDP% 2010'] = pd.to_numeric(df['Agriculture GDP% 2010'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,..,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [101]:
df['Agriculture GDP% 2010'] = df['Agriculture GDP% 2010'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,..,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [102]:
df['Agriculture GDP% 2020'] = pd.to_numeric(df['Agriculture GDP% 2020'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [103]:
df['Agriculture GDP% 2020'] = df['Agriculture GDP% 2020'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,..,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,..,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [104]:
df['Industry GDP% 2010'] = pd.to_numeric(df['Industry GDP% 2010'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [106]:
df['Industry GDP% 2010'] = df['Industry GDP% 2010'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,..,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [107]:
df['Industry GDP% 2020'] = pd.to_numeric(df['Industry GDP% 2020'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [108]:
df['Industry GDP% 2020'] = df['Industry GDP% 2020'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [109]:
df['Manufacturing GDP% 2020'] = pd.to_numeric(df['Manufacturing GDP% 2020'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [110]:
df['Manufacturing GDP% 2020'] = df['Manufacturing GDP% 2020'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,..,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [111]:
df['Manufacturing GDP% 2010'] = pd.to_numeric(df['Manufacturing GDP% 2010'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,NaN,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [112]:
df['Manufacturing GDP% 2010'] = df['Manufacturing GDP% 2010'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,..,..
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,NaN,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [113]:
df['Services GDP% 2020'] = pd.to_numeric(df['Services GDP% 2020'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,..,NaN
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,NaN,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [114]:
df['Services GDP% 2020'] = df['Services GDP% 2020'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,..,NaN
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,NaN,3.7,..,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [115]:
df['Services GDP% 2010'] = pd.to_numeric(df['Services GDP% 2010'], errors='coerce')
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,NaN,NaN
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,NaN,3.7,NaN,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [116]:
df['Services GDP% 2010'] = df['Services GDP% 2010'].astype(float)
df

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
0,Afghanistan,15.9,20.1,26.2,26.8,21.2,14.0,12.5,7.7,48.9,54.7
1,Albania,11.9,15.1,18.0,19.3,24.9,20.0,5.5,6.0,44.0,48.4
2,Algeria,161.2,145.0,8.5,14.1,40.0,20.3,39.0,18.8,39.2,48.7
3,American Samoa,0.6,0.7,NaN,NaN,NaN,NaN,7.2,12.2,NaN,NaN
4,Andorra,3.4,2.9,NaN,0.6,NaN,12.7,NaN,3.7,NaN,79.8
...,...,...,...,...,...,...,...,...,...,...,...
221,Sub-Saharan Africa,1451.8,1706.1,15.9,18.5,27.1,26.5,9.8,11.2,50.9,48.9
222,Low income,613.2,481.0,23.6,26.8,28.3,25.9,4.8,10.7,42.9,39.1
223,Lower middle income,5246.9,7585.5,15.3,16.1,33.0,27.8,16.4,14.9,46.8,48.1
224,Upper middle income,14604.0,22848.3,6.9,7.0,36.7,34.1,21.7,22.1,50.5,55.9
225,High income,45752.2,53699.8,1.3,1.3,23.9,22.4,14.1,13.4,69.0,71.8

In [118]:
df.dtypes

Country                     object
GDP $billions 2010         float64
GDP $billions 2020         float64
Agriculture GDP% 2010      float64
Agriculture GDP% 2020      float64
Industry GDP% 2010         float64
Industry GDP% 2020         float64
Manufacturing GDP% 2010    float64
Manufacturing GDP% 2020    float64
Services GDP% 2010         float64
Services GDP% 2020         float64
dtype: object

In [119]:
df.describe()

,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
count,222.000000,220.000000,209.000000,208.000000,211.000000,209.000000,207.000000,200.00000,208.000000,208.000000
mean,1196.059459,1537.559091,10.976077,10.385577,26.590995,24.887560,11.566184,11.77150,55.117308,57.306731
std,5962.663379,7607.178061,11.200077,10.290354,13.763003,9.919975,6.978658,7.10133,13.636591,12.313578
min,0.000000,0.100000,0.000000,0.000000,4.800000,4.900000,0.400000,0.30000,24.700000,16.800000
25%,5.325000,7.225000,2.200000,2.200000,18.000000,18.100000,6.400000,6.57500,45.850000,49.450000
50%,25.700000,32.050000,6.800000,7.200000,24.500000,23.500000,11.300000,11.20000,54.500000,56.400000
75%,218.525000,257.100000,17.000000,16.450000,31.700000,30.700000,15.600000,15.80000,64.325000,65.700000
max,66596.100000,84906.800000,52.900000,59.500000,75.700000,59.100000,47.300000,48.20000,94.000000,93.900000

In [126]:
df[df['Country']=='Mexico']

,Country,GDP $billions 2010,GDP $billions 2020,Agriculture GDP% 2010,Agriculture GDP% 2020,Industry GDP% 2010,Industry GDP% 2020,Manufacturing GDP% 2010,Manufacturing GDP% 2020,Services GDP% 2010,Services GDP% 2020
125,Mexico,1057.8,1087.1,3.2,3.8,32.4,29.6,15.6,17.2,60.4,60.3

In [122]:
min_gdp10 = df['GDP $billions 2010'].min()
min_gdp10

0.0

In [123]:
df.loc[(df['GDP $billions 2010']==min_gdp10), ['Country', 'GDP $billions 2010']]

    Country  GDP $billions 2010
198  Tuvalu                 0.0

In [128]:
min_gdp20 = df['GDP $billions 2020'].min()
min_gdp20

0.1

In [129]:
df.loc[(df['GDP $billions 2020']==min_gdp20), ['Country', 'GDP $billions 2020']]

    Country  GDP $billions 2020
198  Tuvalu                 0.1

In [131]:
paises_lowgdp = df.loc[(df['GDP $billions 2010']>0) & (df['GDP $billions 2010']<3), ['Country', 'GDP $billions 2010', 'GDP $billions 2020']]
paises_lowgdp

                            Country  GDP $billions 2010  GDP $billions 2020
3                    American Samoa                 0.6                 0.7
6               Antigua and Barbuda                 1.1                 1.4
9                             Aruba                 2.5                 2.5
19                           Belize                 1.4                 1.6
22                           Bhutan                 1.5                 2.3
30                          Burundi                 2.0                 2.8
31                       Cabo Verde                 1.7                 1.7
36         Central African Republic                 2.1                 2.3
44                          Comoros                 0.9                 1.2
51                          Curacao                 2.9                 2.5
55                         Djibouti                 1.1                 3.2
56                         Dominica                 0.5                 0.5
62                          Eritrea                 1.6                 NaN
66                    Faroe Islands                 2.3                 3.2
72                      Gambia, The                 1.5                 1.8
77                        Greenland                 2.5                 3.1
78                          Grenada                 0.8                 1.0
82                    Guinea-Bissau                 0.8                 1.4
101                        Kiribati                 0.2                 0.2
110                         Lesotho                 2.2                 2.3
111                         Liberia                 2.0                 3.0
119                        Maldives                 2.6                 3.7
122                Marshall Islands                 0.2                 0.2
126           Micronesia, Fed. Sts.                 0.3                 0.4
143        Northern Mariana Islands                 0.8                 1.2
147                           Palau                 0.2                 0.3
160                           Samoa                 0.7                 0.8
161                      San Marino                 1.9                 1.5
162           Sao Tome and Principe                 0.2                 0.5
166                      Seychelles                 1.0                 1.2
167                    Sierra Leone                 2.6                 4.1
169       Sint Maarten (Dutch part)                 0.9                 1.2
172                 Solomon Islands                 0.8                 1.5
178             St. Kitts and Nevis                 0.8                 1.0
179                       St. Lucia                 1.5                 1.6
180        St. Martin (French part)                 0.8                 NaN
181  St. Vincent and the Grenadines                 0.7                 0.9
190                     Timor-Leste                 0.9                 1.9
192                           Tonga                 0.4                 0.5
197        Turks and Caicos Islands                 0.7                 0.9
206                         Vanuatu                 0.7                 0.9

In [132]:
max_gdp10 = df['GDP $billions 2010'].max()
max_gdp10

66596.1

In [150]:
paises_maxgdp = df.loc[(df['GDP $billions 2010']>5000) & (df['GDP $billions 2010']<66596.1), ['Country', 'GDP $billions 2010', 'GDP $billions 2020']]
paises_maxgdp

                       Country  GDP $billions 2010  GDP $billions 2020
40                       China              6087.2             14687.7
97                       Japan              5759.1              5040.1
203              United States             15049.0             20893.7
215        East Asia & Pacific             17063.3             27118.7
216      Europe & Central Asia             21025.8             22133.9
217  Latin America & Caribbean              5347.1              4743.2
219              North America             16672.9             22546.0
223        Lower middle income              5246.9              7585.5
224        Upper middle income             14604.0             22848.3
225                High income             45752.2             53699.8

In [151]:
df.to_csv('ProyectoGDP_Paises.csv')