In [3]:
import pandas as pd
import numpy as np
import os
import re

In [30]:
#Toda la información obtenida de el scraping.
columns=['Nombre Comercial','Tipo de vialidad','Nombre de la vialidad','Número exterior',\
        'Edificio. Piso o Nivel','Número Interior','Número de Local','Codigo Postal',\
        'Tipo de asentamiento humano','Nombre asentamiento','Centro Comercial, Parque Industrial, otro',\
        'Nombre','Entrevialidades Tipo1','Nombre1','Tipo 2','Nombre 2','Vialidad Posterior Tipo',\
        'Nombre','Descripción Ubicación Territorial','Entidad Federativa','Delegación o Municipio',\
        'Localidad', 'Datos de Contacto. Telefóno', 'Extensión','E-mail','Otro','Sitio Web',\
        'Perfil General de la Empresa. Tipo', 'Tipo de Instalaciones','¿Exporta?',\
        'Paises','¿Importa?','Paises','Actividad principal', 'Producto o Servicio principal',\
        'Porcentaje','Producto o Servicio principal(2)','Porcentaje','Producto o Servicio principal(2)','Porcentaje',\
        'Actividad(Código)','Principales productos o servicois que ofrece','Destino',\
        'Principales insumos que demanda','Origen','Insumos (2)','Origen (2)',\
        'Insumos (3)','Origen (3)','Facebook', 'Twitter','Grupo Empresarial','Cámara y/o Asociación',\
        'Clúster','Cadena Productiva', 'Distintivo','Nombre Distintivo','Drop']
#Columnas de los datos brutos obtenidos
columns_datos = ['ID','Datos Generales','Perfil General de la Empresa','Actividad Económica']

In [49]:
#Añadiendo en un solo data frame los datos brutos obtenidos del scrapping.
datos =pd.DataFrame()
for i in range(9):
    nombre_archivo = 'Datos_SIEM{}.csv'.format(i)
    datos_nuevos = pd.read_csv(nombre_archivo, usecols=range(0,4),na_values = ['-'])
    datos = pd.concat([datos, datos_nuevos])
datos.reset_index(drop = True,inplace =True)
datos.columns = columns_datos
datos

,ID,Datos Generales,Perfil General de la Empresa,Actividad Económica
0,0,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Sucursal', 'Tip...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
1,1,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Matriz', 'Tipo ...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
2,2,[''],[''],"['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
3,0,[''],[''],"['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
4,1,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Matriz', 'Tipo ...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
...,...,...,...,...
85,16,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
86,17,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
87,18,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
88,19,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
89,20,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."

In [57]:
#Generando una columna con ID único 
id = [i for i in range(1,91)]
datos['ID']= id

,ID,Datos Generales,Perfil General de la Empresa,Actividad Económica
0,1,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Sucursal', 'Tip...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
1,2,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Matriz', 'Tipo ...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
2,3,[''],[''],"['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
3,4,[''],[''],"['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
4,5,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Matriz', 'Tipo ...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
...,...,...,...,...
85,86,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
86,87,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
87,88,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
88,89,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."
89,90,"['NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comer...","['PERFIL', 'Tipo de Empresa', 'Única', 'Tipo d...","['ACTIVIDADES, PRODUCTOS Y SERVICIOS', 'Activi..."

In [251]:
#Trabajando con la primera lista de información Datos Generales
#Limpiando la lista 
print('longitud',len(datos['Datos Generales'][0]))
print( 'tipo de datos',type(datos['Datos Generales'][0]))
lista = datos['Datos Generales'][0].split(',')
#Sustituyendo las comillas qeu tiene de más
lista_limpia = [re.sub(r"\'"," ", element) for element in lista]
#Quitando espacios en blanco 
lista_limpia = [element.strip() for element in lista_limpia]
print(lista_limpia)
print(len(lista_limpia))

longitud 961
tipo de datos <class 'str'>
['[ NOMBRE O DENOMINACIÓN SOCIAL', 'Nombre Comercial', 'VP LIVE', 'UBICACIÓN', 'Tipo de vialidad', 'Calle', 'Nombre de la vialidad', 'ORIENTE 182', 'Número Exterior', '131', 'Edificio. Piso o Nivel', 'NINGUNA', 'Número Interior', 'NINGUNA', 'Número de Local', 'NINGUNO', 'Código Postal', '15530', 'ASENTAMIENTO HUMANO', 'Tipo', 'Colonia', 'Nombre', 'MOCTEZUMA 2DA SECCION', 'CENTRO COMERCIAL', 'PARQUE INDUSTRIAL U OTRO', 'Tipo', 'NINGUNO', 'Nombre', 'NINGUNO', 'ENTREVIALIDADES', 'Tipo 1', 'Calle', 'Nombre 1', 'NORTE 3', 'Tipo 2', 'Avenida', 'Nombre 2', 'NORTE 9', 'VIALIDAD POSTERIOR', 'Tipo', 'Calle', 'Nombre', 'ORIENTE 184', 'UBICACIÓN TERRITORIAL', 'Descripción de ubicación', 'NINGUNA', 'Entidad Federativa', 'Ciudad de México', 'Delegación o Municipio', 'Venustiano Carranza', 'Localidad', 'MEXICO', 'DATOS DE CONTACTO DEL ESTABLECIMIENTO PARA NEGOCIOS', 'Teléfono', '5588419867', 'Extensión', 'NINGUNA', 'E-mail', '-', 'Otro', '-', 'Sitio Web', 'NINGUNA ]']
63

In [198]:
#Buscando las posiciones en lista que tiene información relevante
#Lista con la información que se quiere extraer de los datos brutos de Datos Generales
datos_generales= ['Nombre Comercial','Tipo de vialidad','Nombre de la vialidad','Número Exterior',\
        'Edificio. Piso o Nivel','Número Interior','Número de Local','Código Postal',\
        'ASENTAMIENTO HUMANO','ASENTAMIENTO HUMANO','PARQUE INDUSTRIAL U OTRO',\
        'PARQUE INDUSTRIAL U OTRO', 'Tipo 1','Nombre 1','Tipo 2','Nombre 2','VIALIDAD POSTERIOR',\
        'VIALIDAD POSTERIOR','Descripción de ubicación','Entidad Federativa','Delegación o Municipio',\
        'Localidad', 'Teléfono', 'Extensión','E-mail','Otro','Sitio Web']
#Generando una lista con la posicion -1 de los datos de interes
#hay pocos casos donde se pone la posción -2 o -4, cuando el indicador ser repite.
indices_datos_generales = []
for element in datos_generales :
    indices_datos_generales.append(lista_limpia.index(element))
#len(indices_datos_generales)

27

In [222]:
#Sumando la posición que le correponde para obtener la posición de interés.
posiciones_interes = [0] * (len(indices_datos_generales))
posiciones_interes[0] = indices_datos_generales[0] + 1
for i in range(1,len(indices_datos_generales)):
    #print('{}\n',i)
    if i == len(indices_datos_generales)-1:
        posiciones_interes[i] = indices_datos_generales[i]+1
    elif indices_datos_generales[i-1] == indices_datos_generales[i]:
        posiciones_interes[i]=indices_datos_generales[i]+4
    elif indices_datos_generales[i+1] != indices_datos_generales[i]:
        posiciones_interes[i]=indices_datos_generales[i]+1
    else :  
        posiciones_interes[i]=indices_datos_generales[i]+2
#posiciones_interes

In [225]:
#Generando una lista con los datos de de interes.
datos_generales_columns = [datos_generales[element-1].strip() for element in posiciones_interes]
datos_generales = pd.DataFrame(columns=datos_generales_columns)

In [224]:
datos_generales

Empty DataFrame
Columns: [Nombre Comercial, Tipo de vialidad, Nombre de la vialidad, Número Exterior, Edificio. Piso o Nivel, Número Interior, Número de Local, Código Postal, Tipo, Nombre, Tipo, Nombre, Tipo 1, Nombre 1, Tipo 2, Nombre 2, Tipo, Nombre, Descripción de ubicación, Entidad Federativa, Delegación o Municipio, Localidad, Teléfono, Extensión, E-mail, Otro, Sitio Web]
Index: []

[0 rows x 27 columns]

In [257]:
for i in range(0,90):
    lista = datos['Datos Generales'][i].split(',')
    #Sustituyendo las comillas que tiene de más
    lista_limpia = [re.sub(r"\'"," ", element) for element in lista]
#Quitando espacios en blanco 
    lista_limpia = [element.strip() for element in lista_limpia]
    if len(lista_limpia) < 63 :
        print(i)
    else :
        dg = pd.DataFrame([lista_limpia[element] for element in posiciones_interes]).T
        dg.columns = datos_generales_columns
    datos_generales = pd.concat([datos_generales,dg])
datos_generales

2
3

,Nombre Comercial,Tipo de vialidad,Nombre de la vialidad,Número Exterior,Edificio. Piso o Nivel,Número Interior,Número de Local,Código Postal,Tipo,Nombre,...,Nombre,Descripción de ubicación,Entidad Federativa,Delegación o Municipio,Localidad,Teléfono,Extensión,E-mail,Otro,Sitio Web
0,VP LIVE,Calle,ORIENTE 182,131,NINGUNA,NINGUNA,NINGUNO,15530,Colonia,MOCTEZUMA 2DA SECCION,...,ORIENTE 184,NINGUNA,Ciudad de México,Venustiano Carranza,MEXICO,5588419867,NINGUNA,-,-,NINGUNA ]
0,MARKA ENTERTAINMENT GROUP,Avenida,PRESIDENTE MASARYK,61,9,901,B,11560,Colonia,POLANCO,...,NINGUNO,NINGUNO,Ciudad de México,Miguel Hidalgo,MIGUEL HIDALGO,5575837066,NINGUNO,JURIDICO@MARKA.MX,-,NINGUNO ]
0,MARKA ENTERTAINMENT GROUP,Avenida,PRESIDENTE MASARYK,61,9,901,B,11560,Colonia,POLANCO,...,NINGUNO,NINGUNO,Ciudad de México,Miguel Hidalgo,MIGUEL HIDALGO,5575837066,NINGUNO,JURIDICO@MARKA.MX,-,NINGUNO ]
0,MARKA ENTERTAINMENT GROUP,Avenida,PRESIDENTE MASARYK,61,9,901,B,11560,Colonia,POLANCO,...,NINGUNO,NINGUNO,Ciudad de México,Miguel Hidalgo,MIGUEL HIDALGO,5575837066,NINGUNO,JURIDICO@MARKA.MX,-,NINGUNO ]
0,MARKA ENTERTAINMENT GROUP,Avenida,PRESIDENTE MASARYK,61,9,901,B,11560,Colonia,POLANCO,...,NINGUNO,NINGUNO,Ciudad de México,Miguel Hidalgo,MIGUEL HIDALGO,5575837066,NINGUNO,JURIDICO@MARKA.MX,-,NINGUNO ]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,HOTEL MONTE CASINO,Avenida,INSTITUTO POLITÉCNICO NACIONAL,5104,-,-,-,07370,Colonia,CAPULTITLAN,...,NORTE 1-A,-,Ciudad de México,Gustavo A. Madero,MEXICO,5584005045,-,jvp7@hotmail.com,-,- ]
0,MOTEL LA FLOR,Avenida,INSURGENTES NORTE,1020,-,0,-,07380,Colonia,TLACAMACA,...,INSTITUTO POLITÉCNICO,-,Ciudad de México,Gustavo A. Madero,GUSTAVO A. MADERO,5555175993,-,MOTELLAFLOR@PRODIGY.NET.MX,-,- ]
0,HOTEL TALISMAN,Avenida,TALISMÁN EJE 4 NORTE,4101,-,-,-,7839,Colonia,GERTRUDIS SÁNCHEZ SEGUNDA SECCIÓN,...,ANTONIO RUIZ GALINDO,-,Ciudad de México,Gustavo A. Madero,Gustavo A. Madero,-,-,hoteltalisman4101@gmail.com,-,- ]
0,HOTEL MONTREAL SA DE CV,Calzada,DE TLALPAN,2073,-,-,-,04040,Colonia,PARQUE SAN ANDRÉS,...,VIRGINIA,-,Ciudad de México,Coyoacán,Coyoacán,5556890011,-,-,-,- ]
0,PARAISO PERISUR,Calle,CUSPIDE,53,-,-,-,14010,Colonia,PARQUES DEL PEDREGAL,...,DEL COLLADO,-,Ciudad de México,Tlalpan,TLALPAN,5559275959,-,GACONTA@RADISSON.COM.MX,-,- ]

In [231]:
for i in range(0,len(datos['Datos Generales'])):
    longitud = datos['']

27